Revert "lix: override nix-eval-jobs"
This reverts commit a634a81a80eb372a8a738af144139640e58f9f5d.

nixpkgs-review doesn't work with Lix's nix-eval-jobs:
> error: unrecognised flag '--apply'